// backend/routes/quiz.js
import express from 'express';
import db from '../db.js';
import { nanoid } from 'nanoid';

const router = express.Router();

// Get all quizzes
router.get('/', (req, res) => {
  db.all('SELECT * FROM quizzes', (err, rows) => {
    if (err) return res.status(500).json({ error: err.message });
    res.json(rows);
  });
});

// Create a new quiz (ID generated by backend)
router.post('/', (req, res) => {
  const { name } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'Missing quiz name' });
  }

  const id = nanoid(6).toUpperCase(); // Short, readable quiz ID

  db.run(
    'INSERT INTO quizzes (id, name) VALUES (?, ?)',
         [id, name],
         function (err) {
           if (err) {
             console.error('❌ Error inserting quiz:', err.message);
             return res.status(500).json({ error: 'Database error' });
           }

           res.status(201).json({ id, name });
         }
  );
});

export default router;
